### PR TITLE
Catch and log errors thrown in `rollbackTagPush()` in Git plugin

### LINKED ISSUE #1086: Bug: Error when rolling back git tag release suppresses original error
## Description

When using the `git` plugin to tag a release, the script attempts to push all commits and tags with `git push --follow tags`.  If an error is encountered here it will rollback all changes, and push `git push -d <tag>` to ensure the remote tag is removed.

If the encountered error prevents the tag being created, the `git push -d <tag>` will fail, and throw a new error.  This will then be passed up the chain, and will prevent the original error being logged.

## Issue

A colleague was trying to run a release on our project, but their account was not allowed to push to protected branches.  The `main` branch was protected.  This meant that the push failed, and the tag was not created.  The subsequent deletion of the tag then also failed, as it did not exist on the remote.

The tag deletion error was logged to console, but the original error was not:

```
$ git push --follow-tags
Rolling back remote tag push v1.1.14
$ git push origin --delete v1.1.14
error: unable to delete 'v1.1.14': remote ref does not exist
error: failed to push some refs to 'repo.com:my/repo.git'
ERROR error: unable to delete 'v1.1.14': remote ref does not exist
error: failed to push some refs to 'repo.com:my/repo.git'
```

Adding `this.log.error(error.message)` before the `await` call on line `218 of `node_modules/release-it/lib/plugin/git/Git.js` provides 'actionable' output:

```
$ git push --follow-tags
ERROR remote: GitLab: You are not allowed to push code to protected branches on this project.
To repo.com:my/repo.git
 ! [remote rejected] main -> main (pre-receive hook declined)
 ! [remote rejected] v1.1.14 -> v1.1.14 (pre-receive hook declined)
error: failed to push some refs to 'repo.com:my/repo.git'
Rolling back remote tag push v1.1.14
$ git push origin --delete v1.1.14
error: unable to delete 'v1.1.14': remote ref does not exist
error: failed to push some refs to 'repo.com:my/repo.git'
ERROR error: unable to delete 'v1.1.14': remote ref does not exist
error: failed to push some refs to 'repo.com:my/repo.git'
```

I believe the cause of the incorrect output is in the `catch` block of the `push()` in `node_modules/release-it/lib/plugin/git/Git.js`:

```
  async push({ args = this.options.pushArgs } = {}) {
    const { pushRepo } = this.options;
    const upstreamArgs = await this.getUpstreamArgs(pushRepo);
    try {
      const push = await this.exec(['git', 'push', ...fixArgs(args), ...upstreamArgs]);
      this.disableRollback();
      return push;
    } catch (error) {
      await this.rollbackTagPush();
      throw error;
    }
  }
```

The caught error is never thrown as a new error is thrown when `await this.rollbackTagPush();` fails.  This new error is then passed back up the chain, suppressing the original.

## Steps to reproduce

- Create a new repo with a protected branch
- Authenticate as a user _without_ permission to push to the protected branch
- Configure release-it to push git tags
- Run release-it

### Expected behaviour

The release will fail, with an error that the user cannot push the protected branch

### Actual behaviour

The release fails, with an error that the release tag could not be deleted on the remote

## Full Debug output

```
npx release-it patch --ci -VV

$ git diff --quiet HEAD
$ git rev-parse --abbrev-ref HEAD
main
$ git config --get branch.main.remote
origin
$ git remote get-url origin
git@repo.com:my/repo.git
$ git fetch
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=v* --abbrev=0
v1.1.13
$ git symbolic-ref HEAD
refs/heads/main
$ git for-each-ref --format="%(upstream:short)" refs/heads/main
origin/main
$ npx auto-changelog --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs
- view and edit buttons pointing to legacy site for initial 6 entity types [`faaa187`](https://repo.com/my/repo/commit/faaa187f70df51905d031bb6ddc401cf61b84ef2)
- package-lock.json [`f355e54`](https://repo.com/my/repo/commit/f355e544eecc77df3ad44d6a41a9d9d289bd490d)
🚀 Let's release myrepo (1.1.13...1.1.14)
Changelog:
- view and edit buttons pointing to legacy site for initial 6 entity types [`faaa187`](https://repo.com/my/repo/commit/faaa187f70df51905d031bb6ddc401cf61b84ef2)
- package-lock.json [`f355e54`](https://repo.com/my/repo/commit/f355e544eecc77df3ad44d6a41a9d9d289bd490d)
$ npm version 1.1.14 --no-git-tag-version
v1.1.14
$ npx auto-changelog -p
auto-changelog: Fetching tags…
auto-changelog: 33 version tags found…
auto-changelog: Fetched v1.1.14…
auto-changelog: Fetched v1.1.13…
auto-changelog: Fetched v1.1.12…
auto-changelog: Fetched v1.1.11…
auto-changelog: Fetched v1.1.10…
auto-changelog: Fetched v1.1.9…
auto-changelog: Fetched v1.1.8…
auto-changelog: Fetched v1.1.7…
auto-changelog: Fetched v1.1.6…
auto-changelog: Fetched v1.1.5…
auto-changelog: Fetched v1.1.4…
auto-changelog: Fetched v1.1.3…
auto-changelog: Fetched v1.1.2…
auto-changelog: Fetched v1.1.1…
auto-changelog: Fetched v1.1.0…
auto-changelog: Fetched v1.0.17…
auto-changelog: Fetched v1.0.16…
auto-changelog: Fetched v1.0.15…
auto-changelog: Fetched v1.0.14…
auto-changelog: Fetched v1.0.13…
auto-changelog: Fetched v1.0.12…
auto-changelog: Fetched v1.0.11…
auto-changelog: Fetched v1.0.10…
auto-changelog: Fetched v1.0.9…
auto-changelog: Fetched v1.0.8…
auto-changelog: Fetched v1.0.7…
auto-changelog: Fetched v1.0.6…
auto-changelog: Fetched v1.0.5…
auto-changelog: Fetched v1.0.4…
auto-changelog: Fetched v1.0.3…
auto-changelog: Fetched v1.0.2…
auto-changelog: Fetched v1.0.1…
auto-changelog: Fetched v1.0.0…
auto-changelog: 19 kB written to CHANGELOG.md
$ git status --short --untracked-files=no
 M CHANGELOG.md
 M package-lock.json
 M package.json
Changeset:
 M CHANGELOG.md
 M package-lock.json
 M package.json
$ git add . --update
$ git commit --message Release 1.1.14
[main c3cf35d] Release 1.1.14
 3 files changed, 291 insertions(+), 283 deletions(-)
 rewrite CHANGELOG.md (78%)
$ git tag --annotate --message Release 1.1.14 v1.1.14
$ git symbolic-ref HEAD  [cached]
$ git for-each-ref --format="%(upstream:short)" refs/heads/main  [cached]
$ git push --follow-tags
Rolling back remote tag push v1.1.14
$ git push origin --delete v1.1.14
error: unable to delete 'v1.1.14': remote ref does not exist
error: failed to push some refs to 'repo.com:my/repo.git'
ERROR error: unable to delete 'v1.1.14': remote ref does not exist
error: failed to push some refs to 'repo.com:my/repo.git'
Rolling back changes...
Deleting local tag v1.1.14
$ git tag --delete v1.1.14
Resetting local changes made
$ git reset --hard HEAD~1
auto-changelog: Fetched v1.1.4…
auto-changelog: Fetched v1.1.3…
auto-changelog: Fetched v1.1.2…
auto-changelog: Fetched v1.1.1…
auto-changelog: Fetched v1.1.0…
auto-changelog: Fetched v1.0.17…
auto-changelog: Fetched v1.0.16…
auto-changelog: Fetched v1.0.15…
auto-changelog: Fetched v1.0.14…
auto-changelog: Fetched v1.0.13…
auto-changelog: Fetched v1.0.12…
auto-changelog: Fetched v1.0.11…
auto-changelog: Fetched v1.0.10…
auto-changelog: Fetched v1.0.9…
auto-changelog: Fetched v1.0.8…
auto-changelog: Fetched v1.0.7…
auto-changelog: Fetched v1.0.6…
auto-changelog: Fetched v1.0.5…
auto-changelog: Fetched v1.0.4…
auto-changelog: Fetched v1.0.3…
auto-changelog: Fetched v1.0.2…
auto-changelog: Fetched v1.0.1…
auto-changelog: Fetched v1.0.0…
auto-changelog: 19 kB written to CHANGELOG.md
$ git status --short --untracked-files=no
 M CHANGELOG.md
 M package-lock.json
 M package.json
Changeset:
 M CHANGELOG.md
 M package-lock.json
 M package.json
$ git add . --update
$ git commit --message Release 1.1.14
[main c3cf35d] Release 1.1.14
 3 files changed, 291 insertions(+), 283 deletions(-)
 rewrite CHANGELOG.md (78%)
$ git tag --annotate --message Release 1.1.14 v1.1.14
$ git symbolic-ref HEAD  [cached]
$ git for-each-ref --format="%(upstream:short)" refs/heads/main  [cached]
$ git push --follow-tags
Rolling back remote tag push v1.1.14
$ git push origin --delete v1.1.14
error: unable to delete 'v1.1.14': remote ref does not exist
error: failed to push some refs to 'repo.com:my/repo.git'
ERROR error: unable to delete 'v1.1.14': remote ref does not exist
error: failed to push some refs to 'repo.com:my/repo.git'
Rolling back changes...
Deleting local tag v1.1.14
$ git tag --delete v1.1.14
Resetting local changes made
$ git reset --hard HEAD~1
```

### PR DESCRIPTION
**Pull request by ollyollyollyltd**
Fixes #1086

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @ollyollyollyltd! Totally agree with everything, thanks for explanation + PR! 🙏

**Comment by ollyollyollyltd** [comment]
No probs, thanks for the excellent package :)

Kind regards,

Olly Cross
OllyOllyOlly Ltd

**Comment by webpro** [comment]
J-olly!

**Comment by webpro** [comment]
:rocket: _This pull request is included in v17.2.0. See [Release 17.2.0](https://github.com/release-it/release-it/releases/tag/17.2.0) for release notes._

**Comment by webpro** [comment]
Sorry I forgot to actually _release-it!_

**Pull request merged**
