### PR TITLE
Additional ignored npm ping errors

### PR DESCRIPTION
**Pull request by mafopen**
e.g., https://issues.sonatype.org/browse/NEXUS-13434

### CODE REVIEW

**Comment by mafopen** [comment]
Btw., what's the motivation for: https://github.com/release-it/release-it/blob/master/lib/shell.js#L38
It's kinda annoying that the failed output is printed (seems npm prints the error to stdout and stderr).

**Comment by webpro** [comment]
Just to be sure, would `/(Error |code E)40[04]/` not work (seems to appear in the body of the returned HTML)?

The motivation for that "duplicate" logging, is that indeed sometimes shell programs print to both `stdout` and `stderr`, and there might be relevant output in `stdout` which would otherwise not be printed.

**Comment by mafopen** [comment]
Not in our case, unfortunately:
```
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>404 - Path /-/ping not found in group repository</title>
npm ERR!     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
```

**Comment by webpro** [comment]
Sorry I wasn't clear. I mean in the `<body>` of the HTML document like here: https://issues.sonatype.org/browse/NEXUS-13434?focusedCommentId=505540&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-505540

**Comment by mafopen** [comment]
Sorry for not adding all of it.. but really, it wouldn't match:

```
npm ERR!   <body>
npm ERR!     <h1>404 - Path /-/ping not found in group repository &quot;npm&quot; [id=npm].</h1>
npm ERR!     <p>Path /-/ping not found in group repository &quot;npm&quot; [id=npm].</p>
npm ERR!   </body>
```

**Comment by webpro** [comment]
Sorry for being so stubborn, really trying to keep things as simple as possible here. Thanks!

**Comment by webpro** [comment]
Released in [v12.2.0](https://github.com/release-it/release-it/releases/tag/12.2.0)

**Comment by mafopen** [comment]
No problem at all, I understand that you don't want this to be more complicated than necessary.
Thanks a lot for merging and releasing! And for the great tool in general!

**Pull request merged**
