### PR TITLE
fix: unable to open the browser automatically on Windows system

### PR DESCRIPTION
**Pull request by 13OnTheCode**
Using `await open(url, { wait: true })` can solve the issue of the browser not automatically opening on Windows devices. Additionally, a prompt has been added to the terminal to display the GitHub Release web interface URL, allowing users to manually copy and paste it into the browser for further operation if the browser does not open automatically.

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @13OnTheCode! Will try this when I can from a Windows machine.

The docs of open say that the [`wait` option](https://github.com/sindresorhus/open#wait) can be used to await the app exit, but that shouldn't affect the actual opening. Also:

> On Windows, you have to explicitly specify an app for it to be able to wait.

This PR doesn't seem to do that? Anyway, I'll report back after some testing.

**Comment by 13OnTheCode** [comment]
This is an issue specific to Windows systems, and it has been confirmed by members of the community: 
[https://github.com/sindresorhus/open/issues/298](https://github.com/sindresorhus/open/issues/298)
[https://github.com/pnp/cli-microsoft365/issues/4409](https://github.com/pnp/cli-microsoft365/issues/4409)

The changes I made were based on a solution provided by the community: 
[https://github.com/pnp/cli-microsoft365/issues/4409#issuecomment-1546317412](https://github.com/pnp/cli-microsoft365/issues/4409#issuecomment-1546317412)

Until this issue is completely resolved, I believe this is currently the only available solution

**Comment by webpro** [comment]
Yesterday there were some issues with transitive dependencies in older Node.js versions, eventually decided to do a major release, add a lockfile and drop support for Node.js v14. Once everything seems stable out there I'll merge this!

**Comment by webpro** [comment]
:rocket: _This pull request is included in v16.1.5. See [Release 16.1.5](https://github.com/release-it/release-it/releases/tag/16.1.5) for release notes._

**Comment by webpro** [comment]
Sorry for the wait, @13OnTheCode. Thanks again for the efforts and explanations.

**Comment by 13OnTheCode** [comment]
@webpro Don't worry, and thank you for your work!

**Pull request merged**
