### PR TITLE
Enable use of proxy on GitLab plugin.

### PR DESCRIPTION
**Pull request by BinaryProvider**
Add proxy option to GitLab connections through the use of global-tunnel-ng. Configuration is the same as for the proxy settings on the GitHub plugin.

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @BinaryProvider! Apologies for the late reply, but I already had a refactoring of related tests in the works. Could you please add tests for this PR? Let me know if you need any help.

**Comment by BinaryProvider** [comment]
Thanks @webpro, I've created a basic unit test to check the global proxy setting. Let me know if you'd like something else!

**Comment by webpro** [comment]
Sorry @BinaryProvider, what I tried to say was that you should first merge the `master` branch into yours. Then you can see how the tests have been refactored (not mocking `got`, but using `nock` to mock at the http level now). Apologies for not being clear at first.

**Comment by BinaryProvider** [comment]
Ah, I see, sorry 😊 Sure, I'll take a look at it tomorrow!

**Comment by BinaryProvider** [comment]
@webpro, I've merged the upstream master and modified the unit test accordingly. Looking forward to your input.

**Comment by webpro** [comment]
Not sure what happened, but there are too many changes in this PR (43 files have changed). Looks like you merged the v11 branch or something? Please make sure this PR only contains the necessary changes you intend. Maybe a new branch/PR makes sense? Let me know if you need any help!

**Comment by BinaryProvider** [comment]
Hmm, strange, but you're right. Probably a wise idea to make a new PR from master instead. :)

**Pull request closed without merging**
