### PR TITLE
Investigate Windows test failure

### PR DESCRIPTION
**Pull request by rchl**

### CODE REVIEW

**Comment by rchl** [comment]
Could you also enable it for pull requests?

**Comment by webpro** [comment]
Please fork :)

**Comment by webpro** [comment]
Sorry, I misunderstood. I think it's automatically enabled for branches/PRs.

**Comment by rchl** [comment]
> Sorry, I misunderstood. I think it's automatically enabled for branches/PRs.

I don't think so. I think you need to set
```
on: [push, pull_request]
```

**Pull request closed without merging**
