### PR TITLE
Fixes loading scoped plugins to ensure name is preserved

### LINKED ISSUE #925: Scoped plugin names break context lookup
When updating/renaming our plugins, `release-it-yarn-workspaces` and `release-it-lerna-changelog`, to their new scoped variants, `@release-it-plugins/workspaces` and `@release-it-plugins/lerna-changelog`, our [context lookups are broken](https://github.com/release-it-plugins/workspaces/issues/80). It appears that `release-it` seemingly intentionally (but maybe inadvertently) [strips the scope off the plugin's name](https://github.com/release-it/release-it/blob/ce3a7266b9fe5c6560f31fbf9e3c867de992c652/lib/plugin/factory.js#L40).

It's unclear why it does this. @webpro - is there a reason why plugin names are mutated like this when loading?

### PR DESCRIPTION
**Pull request by scalvert**
Fixes #925

### CODE REVIEW

**Comment by scalvert** [comment]
Looks like the windows tests timed out on unrelated tests 🤷

**Review by rwjblue — APPROVED** [review]

**Comment by scalvert** [comment]
@webpro I had to nudge the timeout up for the interactive tasks tests. LMK if that's a problem!

**Comment by webpro** [comment]
Also commented in the linked issue. I noticed the Windows timeouts a few times before as well, so proper changes, thanks again!

**Comment by webpro** [comment]
It's in [v15.2.0](https://github.com/release-it/release-it/releases/tag/15.2.0)

**Pull request merged**
