### PR TITLE
feat: add Typescript type for config (closes #1052)

### LINKED ISSUE #1052: TypeScript Config file
Just wondering, is there any reason `.ts` isn't included in the list of searches for config files?

Would be nice to make a typed config file.

I'd be happy to submit a PR too :)

### PR DESCRIPTION
**Pull request by JohnCampionJr**
I only added the Config; typing the whole project would only be useful for plugin authors and would be a much larger project.

Sample ts config:
```ts
import type { Config } from 'release-it'

export default {
  plugins: {},
  hooks: {},
  git: {
    commit: true,
    tag: true,
    push: true,
  },
  github: {
    release: true,
  },
  npm: {
    publish: true,
  },
} satisfies Config
```

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @JohnCampionJr! I'm happy to merge it, but is there a way to automate the generation of the `types/config.d.ts` file?

**Comment by JohnCampionJr** [comment]
There probably is but I’m not sure how without moving everything to
typescript. This is more of a stop-gap.

**Comment by ghiscoding** [comment]
Would it be possible to also add brief instructions on 1 of the README so it would be easier for discovery. Thanks

**Comment by JohnCampionJr** [comment]
I've added a bit to the config docs

**Comment by JohnCampionJr** [comment]
Looks like you just did that; I don't see any unrelated changes any more either.

**Comment by webpro** [comment]
And how about adding it to [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped)?

Inspired by https://github.com/JoshuaKGoldberg/release-it-action/issues/29

**Comment by northword** [comment]
Also, I think that the command line arguments (constructor arguments) could include type declarations as well, since they can affect release-it as well. 

example: 

https://github.com/northword/zotero-plugin-scaffold/blob/03ca4f76205e6fa4201ec1a2c14e782c1bb216bd/types/release-it.d.ts#L92-L100

**Comment by webpro** [comment]
Thanks @JohnCampionJr, much appreciated. Sorry it took so long.

**Comment by webpro** [comment]
:rocket: _This pull request is included in v17.4.0. See [Release 17.4.0](https://github.com/release-it/release-it/releases/tag/17.4.0) for release notes._

**Pull request merged**
