### PR TITLE
fix gitlab "is-collaborator" check (adjust API call)

### PR DESCRIPTION
**Pull request by driiftkiing**
I have found a bug, when trying to check if the user is a collaborator.

\
Please feel free to tell me, if I have to change the description. 😄

### CODE REVIEW

**Comment by driiftkiing** [comment]
its seems like, the api `projects/:id/members/all/:id` was introduced in [v12.4.0](https://docs.gitlab.com/ee/api/members.html#get-a-member-of-a-group-or-project-including-inherited-members)

is it possible to add a version check? its not always possible to having the gitlab running at the latest version

**Comment by webpro** [comment]
Another idea is to retry in the `catch` block of the current `isCollaborator` method. Then we don't need a version check, we just try again if the `/members/all/${id}` request fails with a specific error code/response, and then use the `/members/${id}` path instead. What do you think?

**Comment by driiftkiing** [comment]
Yeah, was also thinking about that, but had the idea with the version, because then it's clear why there is choosen another API to get the result.

But we can go also with the `try/catch` block, if you want that.

**Comment by webpro** [comment]
Please also check the type of error. I hope there is a difference between e.g. "endpoint not found" and any other error, in which case we don't need to make an extra request.

**Comment by webpro** [comment]
Thanks @driiftkiing! It's in [v13.5.2](https://github.com/release-it/release-it/releases/tag/13.5.2).

**Pull request merged**
