### PR TITLE
Fix/rollback tag

### PR DESCRIPTION
**Pull request by cakeinpanic**
Hi! 
Fixing issue described in https://github.com/release-it/release-it/issues/1058

I tried to use standard rollback method, but because pushing to remote is async, it does not work on the `exit` hook

If it's crucial to have all rollback in one method, there are few options I have found 
1. Don't call `exit` explicitly and then get ability to use `beforeExit` hook 
2. Export rollback method and explicitly call it before exiting
3. Give a try to https://www.npmjs.com/package/async-kit (did not experiment with it yet)

WDYT?

### CODE REVIEW

**Comment by cakeinpanic** [comment]
@webpro please take a look, this thing is blocking us from using the tool :(

**Comment by webpro** [comment]
Thanks @cakeinpanic! It's an interesting feature, complete with a good test, let's try it out!

**Comment by cakeinpanic** [comment]
@webpro hi! altogether with this fix you have released node 16 deprecation altogether with dependency packages updates.

we are using node 14.20 and can not upgrade to node 17 at the moment

and started getting 
```
> release-it --ci
node_modules/release-it/node_modules/update-notifier/update-notifier.js:148
                options.boxenOptions ??= {
```

is there a way to release also next minor on v16 with this fix only?

**Comment by webpro** [comment]
:rocket: _This pull request is included in v16.3.0. See [Release 16.3.0](https://github.com/release-it/release-it/releases/tag/16.3.0) for release notes._

**Comment by webpro** [comment]
Alright then, although release-it v16 also required Node.js v16

**Comment by webpro** [comment]
I don't fancy going to back to supporting Node.js v14 or earlier, but I'll happily accept fixes against the v16 branch.

**Comment by cakeinpanic** [comment]
@webpro thank you for fast response! release v 16 actually works fine with node 14 🫠 
but with a warning 
```
UnhandledPromiseRejectionWarning: TypeError: Intl.Segmenter is not a constructor
    at stringWidth (file:///node_modules/release-it/node_modules/ora/node_modules/string-width/index.js:27:37)
```

but i have made a mistake, we are using version 15 in our repos...

I have actually found an uuuugly workaround using hooks, since revert of published tag is not our only issue – we dont want to publish an npm package at all if we ar enot able to push, so with my hook workaround this fix is not even needed :)

**Comment by webpro** [comment]
lol

**Pull request merged**
