### PR TITLE
feat: create tag via Gitlab release (#1115)

### PR DESCRIPTION
**Pull request by afrimberger**
Create tag via Gitlab release #1115

### CODE REVIEW

**Comment by afrimberger** [comment]
I tested the following cases with a "real" Gitlab installation:
1. Tag doesn't exist: Release and Tag are created
2. Tag exists but not the release: Release is created
3. Tag and release are created: Gitlab throws `ERROR Response code 409 (Conflict)`

@webpro : Please have a look at it

**Comment by webpro** [comment]
Thanks @afrimberger, I'm happy to merge this but test(s) seem failing. Any chance you could take a look?

**Comment by robross0606** [comment]
I checked out this project and cannot even get `npm ci` to work on Node 18.  There are conflicting peer dependencies:
```
C:\Code\public\release-it>npm ci             
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: eslint-plugin-import@2.29.1
npm error Found: eslint@9.3.0
npm error node_modules/eslint
npm error   dev eslint@"9.3.0" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm error   node_modules/@eslint-community/eslint-utils
npm error     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.3.0
npm error   4 more (eslint-config-prettier, eslint-plugin-ava, ...)
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm error node_modules/eslint-plugin-import
npm error   dev eslint-plugin-import@"2.29.1" from the root project
npm error
npm error Conflicting peer dependency: eslint@8.57.1
npm error node_modules/eslint
npm error   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm error   node_modules/eslint-plugin-import
npm error     dev eslint-plugin-import@"2.29.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by robross0606** [comment]
Nevermind, I see that `--legacy-peer-deps` are necessary from the GitHub action file.

**Comment by robross0606** [comment]
After reviewing this, I don't think the MR is complete even insofar as capabilities.  We would also want to be able to pass `tag_message` to the GitLab API or else we would lose fidelity available via regular `git` tagging.  The errors to do look like `nock` mismatches, but I'm not yet familiar enough with either `ava` or `nock` to fix them.

**Comment by robross0606** [comment]
I have test fixes here.  How shall I proceed?  Should I fork from here and submit a separate MR?

**Comment by webpro** [comment]
> Nevermind, I see that `--legacy-peer-deps` are necessary from the GitHub action file.

That flag shouldn't be necessary anymore. Maybe it still was in this somewhat dated branch.

> I have test fixes here for the `nock` interceptor problems. How shall I proceed? Should I fork from here and submit a separate MR?

Sounds good! A new pull request branched from main would probably better so we're not depending on @afrimberger for completion, and you wouldn't need to rebase.

**Comment by robross0606** [comment]
> Sounds good! A new pull request branched from main would probably better so we're not depending on @afrimberger for completion, and you wouldn't need to rebase.

Okay, this is odd.  I forked from the latest `main` and applied my changes.  Now all the tests are failing with "exited with a non-zero exit code: 1" up front but with _zero_ reasons.  Just all "uncaught exceptions" with no stack traces.  At least @afrimberger's branch provided stack traces when `ava` failed.  Whatever has changed in the mainline branch is hiding error reasons.  I don't know how I would hunt this down without stacks.

**Comment by robross0606** [comment]
> Sounds good! A new pull request branched from main would probably better so we're not depending on @afrimberger for completion, and you wouldn't need to rebase.

MR #1161 is up.

**Comment by webpro** [comment]
Closing this as #1161 is merged.

**Pull request closed without merging**
