### PR TITLE
Added local test instructions to help new contributors

### PR DESCRIPTION
**Pull request by nidkil**
Added instructions how to test locally to help new contributors to get up and running quickly.

### CODE REVIEW

**Comment by nidkil** [comment]
Added additional instructions to help new contributors getting up and running.

**Comment by webpro** [comment]
Thanks, @nidkil! Great idea to better help out new contributors. I think I prefer to link to external tutorials or instructions on how to fork and submit a pull request etc., though.

The command to test locally might work, but the `npm link` is meant to be able to do for example `release-it --verbose`. Or didn't that work for you?

**Comment by nidkil** [comment]
Yes `release-it --verbose` worked. The `npm link` might be confusing.

I think the instructions to join and merge with the upstream repo has added value. I guess it is a matter of preference :-)

**Comment by webpro** [comment]
I updated https://github.com/webpro/release-it/blob/master/CONTRIBUTING.md, hope you like it :-)

**Pull request closed without merging**
