### PR TITLE
Remove `node-fetch` and `got` from dependencies

### PR DESCRIPTION
**Pull request by hyoban**
Continue #1120. Hope my changes are correct

Why change ci?
- https://github.com/npm/cli/issues/7657
- https://github.com/nodejs/node/issues/53902#issuecomment-2239263377

### CODE REVIEW

**Comment by webpro** [comment]
Excellent! I want to merge it right away, but also not sure what might break subtly in certain cases after removing such "core" dependencies. I think it's best to have a major bump with this. All tests pass so that's a good start!

**Comment by webpro** [comment]
Thanks @hyoban! Going to make it a major bump along with some more dependency updates.

**Comment by hyoban** [comment]
Thanks, hope I didn't introduce some bugs

**Comment by webpro** [comment]
It's in the `v18` branch and you could try using eg. `pnpm i https://pkg.pr.new/release-it@21826ed` if you need it or want to play with it already

**Comment by webpro** [comment]
:rocket: _This pull request is included in v18.0.0-next.0. See [Release 18.0.0-next.0](https://github.com/release-it/release-it/releases/tag/18.0.0-next.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This pull request is included in v17.7.0. See [Release 17.7.0](https://github.com/release-it/release-it/releases/tag/17.7.0) for release notes._

**Pull request merged**
