### PR TITLE
Account for custom tag name when retrieving latest tag

### PR DESCRIPTION
**Pull request by SuaYoo**
Addresses https://github.com/release-it/release-it/issues/708, based on @jsamr's suggestion (https://github.com/release-it/release-it/issues/708#issuecomment-704942925)

## Context

We're differentiating releases between monorepo packages by prefixing tags with `packageName/v`. I realized that the latest tag applied to the entire repo, which was not the behavior I expected when specifying a custom `tagName`.

Prior to proposed changes, you can see that running `release-it` for a package named "react-client" returns the latest tag for the "webrtc" package, which is in the same repo:
```sh
$ git describe --tags --abbrev=0  [cached]
  release-it:config { latestTag: 'webrtc/v2.2.5' } +3ms
# ... truncated
  release-it:config { name: 'webrtc',
  release-it:config   latestVersion: '1.0.0',
  release-it:config   version: undefined,
  release-it:config   changelog:
  release-it:config    '### [1.0.1](https://github.com/team-telnyx/webrtc/compare/webrtc/v2.2.5...react-client/v1.0.1) (2021-01-06)\n\n\n### Features\n\n* Generate API docs from TS ([#115](https://github.com/team-telnyx/webrtc/issues/115)) ([66882d2](https://github.com/team-telnyx/webrtc/commit/66882d28f41ec458d6f28d4f54d218e21a780cfd))' } +405ms
```

Both latest tag and conventional-changelog works as expected after applying proposed changes:
```sh
$ git describe --tags --match "react-client/v*" --abbrev=0  [cached]
  release-it:config { latestTag: 'react-client/v1.0.0' } +4ms
# ... truncated
  release-it:config { name: 'webrtc',
  release-it:config   latestVersion: '1.0.0',
  release-it:config   version: undefined,
  release-it:config   changelog:
  release-it:config    '### [1.0.1](https://github.com/team-telnyx/webrtc/compare/react-client/v1.0.0...react-client/v1.0.1) (2021-01-06)\n\n\n### Features\n\n* Generate API docs from TS ([#115](https://github.com/team-telnyx/webrtc/issues/115)) ([66882d2](https://github.com/team-telnyx/webrtc/commit/66882d28f41ec458d6f28d4f54d218e21a780cfd))' } +395ms
```

### CODE REVIEW

**Comment by SuaYoo** [comment]
Seeing a test fail with `fatal: ambiguous argument '2.0.1': unknown revision or path not in the working tree.` that I can't replicate locally, investigating

**Comment by SuaYoo** [comment]
@webpro, any insight on the failing test?

**Comment by webpro** [comment]
Thanks @SuaYoo! Looks good.

The failing test is caused by the fact that the tags are not fetched in the github action, and the stub for this command was missing in the test. I added the stubs in the master branch (in e56f3786fada7e82e97146a40aecb5e0985973ea), so could you please merge this to your PR branch?

**Comment by SuaYoo** [comment]
Thanks @webpro, tests are passing now.

Side note, on the subject of stubs--minor issue but it seems the upstream URL stub for `should release to git.pushRepo` isn't working. https://github.com/release-it/release-it/issues/730

**Pull request merged**
